### ISSUE TITLE
Change language switcher representation

### ISSUE THREAD

**Issue by vitaliidasaev** [OpenMAVN/MAVN.FrontEnd.BackOffice#41]
To show the LANGUAGE FLAGS right on the menu and not as a dropdown.
Comment menu (maybe for future changes) and for now to show all languages.

Notes: In future it depends how many languages we plan to implement - dropdown is convenient for 3+ items.
If it will be up to 3 now then all languages should be visible.

**Comment by vitaliidasaev** [comment]
@nickanastasov please comment to assign.

**Comment by nickanastasov** [comment]
I will take this task.
