### ISSUE TITLE
Create Admin Portal email verification page

### ISSUE THREAD

**Issue by vitaliidasaev** [OpenMAVN/MAVN.FrontEnd.BackOffice#51]
the page should be similar to https://github.com/OpenMAVN/MAVN.FrontEnd.CustomerWebsite/tree/master/src/app/public/email-confirmation

see parent story description: https://github.com/openmavn/pm/issues/51

**Comment by vitaliidasaev** [comment]
@nickanastasov please comment to assign

**Comment by nickanastasov** [comment]
I will take this task.

**Comment by vitaliidasaev** [comment]
deployed
